version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_DATABASE_NAME: postgres
      DB_PORT: 5432
      API_SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      API_ALGORITHM: HS256
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
